In [2]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("database.sqlite")

In [3]:
query = """
SELECT
    oi.row_id,
    oi.order_key,
    oi.product_id,
    oi.discount,
    oi.quantity,
    oi.sales,
    oi.profit,
    oi.shipping_cost,
    oi.year,
    oi.week_num,
    o.order_date,
    o.ship_date,
    o.ship_mode,
    o.order_priority,
    o.customer_id,
    o.location_id,
    c.customer_name,
    c.segment,
    p.category,
    p.sub_category,
    p.product_name,
    l.city,
    l.state,
    l.country,
    l.region,
    l.market
FROM order_items oi
JOIN orders o ON oi.order_key = o.order_key
JOIN dim_customers c ON o.customer_id = c.customer_id
JOIN dim_products p ON oi.product_id = p.product_id
JOIN dim_locations l ON o.location_id = l.location_id
"""

df = pd.read_sql_query(query, conn)

In [4]:
print(df.shape)
df.head()

(51290, 26)

,row_id,order_key,product_id,discount,quantity,sales,profit,shipping_cost,year,week_num,...,customer_name,segment,category,sub_category,product_name,city,state,country,region,market
0,1,MX-2014-143658_SC-205753,OFF-LA-10002782,0.0,3,13.0,4.56,1.033,2014,40,...,Sonia Cooley,Consumer,Office Supplies,Labels,"Hon File Folder Labels, Adjustable",Mexico City,Distrito Federal,Mexico,North,LATAM
1,2,MX-2012-155047_KW-165703,FUR-FU-10004015,0.0,8,252.0,90.72,13.449,2012,42,...,Kelly Williams,Consumer,Furniture,Furnishings,"Tenex Clock, Durable",Dos Quebradas,Risaralda,Colombia,South,LATAM
2,3,MX-2012-155047_KW-165703,FUR-BO-10002352,0.0,2,193.0,54.08,9.627,2012,42,...,Kelly Williams,Consumer,Furniture,Bookcases,"Ikea 3-Shelf Cabinet, Mobile",Dos Quebradas,Risaralda,Colombia,South,LATAM
3,4,MX-2012-155047_KW-165703,OFF-BI-10004428,0.0,4,35.0,4.96,1.371,2012,42,...,Kelly Williams,Consumer,Office Supplies,Binders,"Cardinal Binder, Clear",Dos Quebradas,Risaralda,Colombia,South,LATAM
4,5,MX-2012-155047_KW-165703,OFF-AR-10004594,0.0,2,72.0,11.44,3.787,2012,42,...,Kelly Williams,Consumer,Office Supplies,Art,"Sanford Canvas, Water Color",Dos Quebradas,Risaralda,Colombia,South,LATAM

In [5]:
df['order_date'] = pd.to_datetime(df['order_date'])
df['ship_date'] = pd.to_datetime(df['ship_date'])

In [6]:
df[['order_date', 'ship_date']].head()

  order_date  ship_date
0 2014-10-02 2014-10-06
1 2012-10-15 2012-10-20
2 2012-10-15 2012-10-20
3 2012-10-15 2012-10-20
4 2012-10-15 2012-10-20